rootLogger.level = INFO
rootLogger.appenderRef.console.ref = ConsoleAppender
logger.kafka.name = org.apache.kafka
logger.kafka.level = WARN
appender.console.name = ConsoleAppender
appender.console.type = CONSOLE
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = {"timestamp":"%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}","level":"%p","logger":"%c","message":"%enc{%m}{JSON}","exception":"%enc{%xEx}{JSON}"}%n
